/* Generated by tools/codegen.mjs — do not edit by hand. */
/* SPDX-License-Identifier: Apache-2.0 */

export const STANDART_REGISTRY_VERSION = "0.2.0" as const;
export const STANDART_REGISTRY_CHECKSUM = "sha256:7f7342974eb2f7d298305eb9d256d386cfd70a905cbf717ee655091b5163a6db" as const;

export type StandartSid =
  | "069b2a4c"
  | "84ca530f"
  | "faa74c01"
  | "3d53bc7d"
  | "be792b1c"
  | "e867039a"
  | "392bf836"
  | "8ff90c08"
  | "653381be"
  | "e34550dd"
  | "1f09fed4"
  | "df404cc2"
  | "6f419740"
  | "8d5c8d19"
  | "9744622b"
  | "029cf91b"
  | "81f1695e"
  | "749128cc"
  | "705c5b61"
  | "a4d3f616"
  | "991ae51b"
  | "94346493"
  | "f31fa92e"
  | "bd0ff19a"
  | "0d1c3212"
  | "24d3556f"
  | "5ab774ed"
  | "d26a38e1"
  | "4214c166"
  | "0abf6ccc"
  | "1f1db238"
  | "7ec38c5b"
  | "1d94ea87"
  | "67b72924"
  | "d38e7705"
  | "b0209dc2"
  | "8c138cb4"
  | "c0154acf"
  | "99e3d569"
  | "993c1f96"
  | "59be49ea"
  | "fb2badbe"
  | "f0af635e";

export type StandartPath =
  | "actuation.command"
  | "actuation.power"
  | "actuation.setpoint"
  | "identity.device"
  | "identity.mac"
  | "identity.serial"
  | "identity.uuid"
  | "logical.flag"
  | "logical.level"
  | "logical.mode"
  | "media.audio_ref"
  | "media.image_ref"
  | "network.rssi"
  | "network.uptime"
  | "physical.electrical.battery_soc"
  | "physical.electrical.current"
  | "physical.electrical.energy"
  | "physical.electrical.frequency"
  | "physical.electrical.power"
  | "physical.electrical.voltage"
  | "physical.environment.co2"
  | "physical.environment.humidity"
  | "physical.environment.illuminance"
  | "physical.environment.pm25"
  | "physical.environment.pressure"
  | "physical.environment.temperature"
  | "physical.environment.voc"
  | "physical.geo.altitude"
  | "physical.geo.geopoint"
  | "physical.geo.heading"
  | "physical.health.body_temp"
  | "physical.health.heart_rate"
  | "physical.health.spo2"
  | "physical.mechanical.flow"
  | "physical.mechanical.force"
  | "physical.mechanical.pressure_gauge"
  | "physical.mechanical.torque"
  | "physical.motion.acceleration"
  | "physical.motion.position"
  | "physical.motion.rotation"
  | "physical.motion.velocity"
  | "temporal.duration"
  | "temporal.timestamp";

export type StandartProfileId =
  | "actuator"
  | "gps"
  | "meter"
  | "thermometer";

export type StandartKind =
  | "quantity"
  | "enum"
  | "identity"
  | "temporal"
  | "spatial"
  | "logical"
  | "media"
  | "structured"
  | "event"
  | "command";

export type StandartEncoding =
  | "bool"
  | "u8"
  | "i16"
  | "i32"
  | "f32"
  | "f64"
  | "utf8"
  | "bytes"
  | "record"
  | "enum";

export type StandartSensitivity = "public" | "internal" | "personal" | "restricted";
export type StandartStatus = "stable" | "draft" | "deprecated";

export interface LocalizedString {
  ru: string;
  en: string;
}

export interface StandartTypeCard {
  sid: StandartSid;
  path: StandartPath;
  kind: StandartKind;
  unit: string;
  encodings: StandartEncoding[];
  sensitivity: StandartSensitivity;
  status: StandartStatus;
  title: LocalizedString;
  fingerprint: string;
  aliases?: { ru?: string; short?: string; legacy?: string };
  description?: LocalizedString;
  range?: { min: number; max: number; unit?: string };
  enumValues?: string[];
}

export interface StandartProfile {
  id: StandartProfileId;
  version: string;
  title: LocalizedString;
  description?: LocalizedString;
  required: StandartSid[];
  optional: StandartSid[];
}

/** Minimum wire reading: device sends sid + value */
export interface StandartReading {
  sid: StandartSid;
  v: unknown;
  t?: number;
}

/** Short ids for wire / firmware */
export const Sid = {
  ACTUATION_COMMAND: "069b2a4c" as const,
  ACTUATION_POWER: "84ca530f" as const,
  ACTUATION_SETPOINT: "faa74c01" as const,
  IDENTITY_DEVICE: "3d53bc7d" as const,
  IDENTITY_MAC: "be792b1c" as const,
  IDENTITY_SERIAL: "e867039a" as const,
  IDENTITY_UUID: "392bf836" as const,
  LOGICAL_FLAG: "8ff90c08" as const,
  LOGICAL_LEVEL: "653381be" as const,
  LOGICAL_MODE: "e34550dd" as const,
  MEDIA_AUDIO_REF: "1f09fed4" as const,
  MEDIA_IMAGE_REF: "df404cc2" as const,
  NETWORK_RSSI: "6f419740" as const,
  NETWORK_UPTIME: "8d5c8d19" as const,
  PHYSICAL_ELECTRICAL_BATTERY_SOC: "9744622b" as const,
  PHYSICAL_ELECTRICAL_CURRENT: "029cf91b" as const,
  PHYSICAL_ELECTRICAL_ENERGY: "81f1695e" as const,
  PHYSICAL_ELECTRICAL_FREQUENCY: "749128cc" as const,
  PHYSICAL_ELECTRICAL_POWER: "705c5b61" as const,
  PHYSICAL_ELECTRICAL_VOLTAGE: "a4d3f616" as const,
  PHYSICAL_ENVIRONMENT_CO2: "991ae51b" as const,
  PHYSICAL_ENVIRONMENT_HUMIDITY: "94346493" as const,
  PHYSICAL_ENVIRONMENT_ILLUMINANCE: "f31fa92e" as const,
  PHYSICAL_ENVIRONMENT_PM25: "bd0ff19a" as const,
  PHYSICAL_ENVIRONMENT_PRESSURE: "0d1c3212" as const,
  PHYSICAL_ENVIRONMENT_TEMPERATURE: "24d3556f" as const,
  PHYSICAL_ENVIRONMENT_VOC: "5ab774ed" as const,
  PHYSICAL_GEO_ALTITUDE: "d26a38e1" as const,
  PHYSICAL_GEO_GEOPOINT: "4214c166" as const,
  PHYSICAL_GEO_HEADING: "0abf6ccc" as const,
  PHYSICAL_HEALTH_BODY_TEMP: "1f1db238" as const,
  PHYSICAL_HEALTH_HEART_RATE: "7ec38c5b" as const,
  PHYSICAL_HEALTH_SPO2: "1d94ea87" as const,
  PHYSICAL_MECHANICAL_FLOW: "67b72924" as const,
  PHYSICAL_MECHANICAL_FORCE: "d38e7705" as const,
  PHYSICAL_MECHANICAL_PRESSURE_GAUGE: "b0209dc2" as const,
  PHYSICAL_MECHANICAL_TORQUE: "8c138cb4" as const,
  PHYSICAL_MOTION_ACCELERATION: "c0154acf" as const,
  PHYSICAL_MOTION_POSITION: "99e3d569" as const,
  PHYSICAL_MOTION_ROTATION: "993c1f96" as const,
  PHYSICAL_MOTION_VELOCITY: "59be49ea" as const,
  TEMPORAL_DURATION: "fb2badbe" as const,
  TEMPORAL_TIMESTAMP: "f0af635e" as const,
} as const;

/** Full hierarchical paths */
export const Path = {
  ACTUATION_COMMAND: "actuation.command" as const,
  ACTUATION_POWER: "actuation.power" as const,
  ACTUATION_SETPOINT: "actuation.setpoint" as const,
  IDENTITY_DEVICE: "identity.device" as const,
  IDENTITY_MAC: "identity.mac" as const,
  IDENTITY_SERIAL: "identity.serial" as const,
  IDENTITY_UUID: "identity.uuid" as const,
  LOGICAL_FLAG: "logical.flag" as const,
  LOGICAL_LEVEL: "logical.level" as const,
  LOGICAL_MODE: "logical.mode" as const,
  MEDIA_AUDIO_REF: "media.audio_ref" as const,
  MEDIA_IMAGE_REF: "media.image_ref" as const,
  NETWORK_RSSI: "network.rssi" as const,
  NETWORK_UPTIME: "network.uptime" as const,
  PHYSICAL_ELECTRICAL_BATTERY_SOC: "physical.electrical.battery_soc" as const,
  PHYSICAL_ELECTRICAL_CURRENT: "physical.electrical.current" as const,
  PHYSICAL_ELECTRICAL_ENERGY: "physical.electrical.energy" as const,
  PHYSICAL_ELECTRICAL_FREQUENCY: "physical.electrical.frequency" as const,
  PHYSICAL_ELECTRICAL_POWER: "physical.electrical.power" as const,
  PHYSICAL_ELECTRICAL_VOLTAGE: "physical.electrical.voltage" as const,
  PHYSICAL_ENVIRONMENT_CO2: "physical.environment.co2" as const,
  PHYSICAL_ENVIRONMENT_HUMIDITY: "physical.environment.humidity" as const,
  PHYSICAL_ENVIRONMENT_ILLUMINANCE: "physical.environment.illuminance" as const,
  PHYSICAL_ENVIRONMENT_PM25: "physical.environment.pm25" as const,
  PHYSICAL_ENVIRONMENT_PRESSURE: "physical.environment.pressure" as const,
  PHYSICAL_ENVIRONMENT_TEMPERATURE: "physical.environment.temperature" as const,
  PHYSICAL_ENVIRONMENT_VOC: "physical.environment.voc" as const,
  PHYSICAL_GEO_ALTITUDE: "physical.geo.altitude" as const,
  PHYSICAL_GEO_GEOPOINT: "physical.geo.geopoint" as const,
  PHYSICAL_GEO_HEADING: "physical.geo.heading" as const,
  PHYSICAL_HEALTH_BODY_TEMP: "physical.health.body_temp" as const,
  PHYSICAL_HEALTH_HEART_RATE: "physical.health.heart_rate" as const,
  PHYSICAL_HEALTH_SPO2: "physical.health.spo2" as const,
  PHYSICAL_MECHANICAL_FLOW: "physical.mechanical.flow" as const,
  PHYSICAL_MECHANICAL_FORCE: "physical.mechanical.force" as const,
  PHYSICAL_MECHANICAL_PRESSURE_GAUGE: "physical.mechanical.pressure_gauge" as const,
  PHYSICAL_MECHANICAL_TORQUE: "physical.mechanical.torque" as const,
  PHYSICAL_MOTION_ACCELERATION: "physical.motion.acceleration" as const,
  PHYSICAL_MOTION_POSITION: "physical.motion.position" as const,
  PHYSICAL_MOTION_ROTATION: "physical.motion.rotation" as const,
  PHYSICAL_MOTION_VELOCITY: "physical.motion.velocity" as const,
  TEMPORAL_DURATION: "temporal.duration" as const,
  TEMPORAL_TIMESTAMP: "temporal.timestamp" as const,
} as const;

export const TYPES: readonly StandartTypeCard[] = [
  {
    "sid": "069b2a4c",
    "path": "actuation.command",
    "kind": "command",
    "unit": "-",
    "encodings": [
      "enum",
      "utf8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Команда",
      "en": "Command"
    },
    "fingerprint": "sha256:069b2a4c6275db20831f2ccbd10895b91d46f2eb067e07312f30a27962c69468",
    "aliases": {
      "legacy": "std:act.command",
      "short": "actuation.command"
    },
    "enumValues": [
      "start",
      "stop",
      "reset",
      "open",
      "close",
      "toggle"
    ],
    "description": {
      "ru": "Команда воздействия на исполнительный механизм.",
      "en": "Actuation command for an actuator."
    }
  },
  {
    "sid": "84ca530f",
    "path": "actuation.power",
    "kind": "enum",
    "unit": "-",
    "encodings": [
      "enum",
      "bool"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Питание / включение",
      "en": "Power on/off"
    },
    "fingerprint": "sha256:84ca530f4603358344946ae8ea50e5da13a00a17cb26578c612435386e050904",
    "aliases": {
      "legacy": "std:act.power",
      "short": "actuation.power"
    },
    "enumValues": [
      "off",
      "on"
    ],
    "description": {
      "ru": "Состояние питания или включения актуатора.",
      "en": "Power or actuator on/off state."
    }
  },
  {
    "sid": "faa74c01",
    "path": "actuation.setpoint",
    "kind": "quantity",
    "unit": "-",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Уставка",
      "en": "Setpoint"
    },
    "fingerprint": "sha256:faa74c0149bddf016e09217531f24a1365062b383e71a259e562e81cf34d9c49",
    "aliases": {
      "legacy": "std:act.setpoint",
      "short": "actuation.setpoint"
    },
    "description": {
      "ru": "Целевое значение для регулятора; единица уточняется приложением или профилем.",
      "en": "Target value for a controller; unit is application- or profile-specific."
    }
  },
  {
    "sid": "3d53bc7d",
    "path": "identity.device",
    "kind": "identity",
    "unit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Идентификатор устройства",
      "en": "Device identifier"
    },
    "fingerprint": "sha256:3d53bc7da637a0cf8389d4ee5fc7c47b8c4e0455ab6068e828d9489f8fef20df",
    "aliases": {
      "legacy": "std:id.device",
      "short": "identity.device"
    },
    "description": {
      "ru": "Стабильный идентификатор устройства (рекомендуется urn:std:id:dev:...).",
      "en": "Stable device identifier (recommended urn:std:id:dev:...)."
    }
  },
  {
    "sid": "be792b1c",
    "path": "identity.mac",
    "kind": "identity",
    "unit": "-",
    "encodings": [
      "utf8",
      "bytes"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "MAC-адрес",
      "en": "MAC address"
    },
    "fingerprint": "sha256:be792b1c857d3ae84fccb1464bc3abb7eba1103991cccaf1bd4c05bcb27208e3",
    "aliases": {
      "legacy": "std:id.mac",
      "short": "identity.mac"
    },
    "description": {
      "ru": "Аппаратный MAC-адрес (строка или 6 байт).",
      "en": "Hardware MAC address (string or 6 bytes)."
    }
  },
  {
    "sid": "e867039a",
    "path": "identity.serial",
    "kind": "identity",
    "unit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Серийный номер",
      "en": "Serial number"
    },
    "fingerprint": "sha256:e867039afbd3ff6c019b19adc4cb6f6b4addd36e54bc9b0d5d32a9d75573e869",
    "aliases": {
      "legacy": "std:id.serial",
      "short": "identity.serial"
    },
    "description": {
      "ru": "Серийный номер производителя.",
      "en": "Manufacturer serial number."
    }
  },
  {
    "sid": "392bf836",
    "path": "identity.uuid",
    "kind": "identity",
    "unit": "-",
    "encodings": [
      "utf8",
      "bytes"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "UUID",
      "en": "UUID"
    },
    "fingerprint": "sha256:392bf836d277e0d3de622bff67fb892b6bbc7b883b597ec502cefff20c234fad",
    "aliases": {
      "legacy": "std:id.uuid",
      "short": "identity.uuid"
    },
    "description": {
      "ru": "Универсальный уникальный идентификатор (строка или 16 байт).",
      "en": "Universally unique identifier (string or 16 bytes)."
    }
  },
  {
    "sid": "8ff90c08",
    "path": "logical.flag",
    "kind": "logical",
    "unit": "-",
    "encodings": [
      "bool",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Флаг",
      "en": "Flag"
    },
    "fingerprint": "sha256:8ff90c0827885a1ff25c834173367647539d550e5c736d25ce278aaa7863e12c",
    "aliases": {
      "legacy": "std:logical.flag",
      "short": "logical.flag"
    },
    "description": {
      "ru": "Логический флаг true/false.",
      "en": "Boolean flag true/false."
    }
  },
  {
    "sid": "653381be",
    "path": "logical.level",
    "kind": "quantity",
    "unit": "%",
    "encodings": [
      "u8",
      "f32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Уровень",
      "en": "Level"
    },
    "fingerprint": "sha256:653381beaefc1f3f67c41f98a859261be291e0696a50fb79dc2b0332d865f8a8",
    "aliases": {
      "legacy": "std:logical.level",
      "short": "logical.level"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Нормированный уровень 0–100%.",
      "en": "Normalized level 0–100%."
    }
  },
  {
    "sid": "e34550dd",
    "path": "logical.mode",
    "kind": "enum",
    "unit": "-",
    "encodings": [
      "enum",
      "utf8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Режим",
      "en": "Mode"
    },
    "fingerprint": "sha256:e34550dd3b50b0aafbe928e30dab7db5598b069817d1bca599d113888f6243ca",
    "aliases": {
      "legacy": "std:logical.mode",
      "short": "logical.mode"
    },
    "enumValues": [
      "off",
      "on",
      "auto",
      "sleep",
      "error"
    ],
    "description": {
      "ru": "Общий режим работы устройства.",
      "en": "Generic device operating mode."
    }
  },
  {
    "sid": "1f09fed4",
    "path": "media.audio_ref",
    "kind": "media",
    "unit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Ссылка на аудио",
      "en": "Audio reference"
    },
    "fingerprint": "sha256:1f09fed46dede8efb64c55594a7c1fa085f24a8599fae30b1ddf30acd73960e0",
    "aliases": {
      "legacy": "std:media.audio_ref",
      "short": "media.audio_ref"
    },
    "description": {
      "ru": "URI или путь к аудиофайлу.",
      "en": "URI or path to an audio resource."
    }
  },
  {
    "sid": "df404cc2",
    "path": "media.image_ref",
    "kind": "media",
    "unit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Ссылка на изображение",
      "en": "Image reference"
    },
    "fingerprint": "sha256:df404cc21caa34244933fd1918d4c14bafb81ef6989588145bf9989795d9e681",
    "aliases": {
      "legacy": "std:media.image_ref",
      "short": "media.image_ref"
    },
    "description": {
      "ru": "URI или путь к изображению.",
      "en": "URI or path to an image."
    }
  },
  {
    "sid": "6f419740",
    "path": "network.rssi",
    "kind": "quantity",
    "unit": "dB",
    "encodings": [
      "i16",
      "f32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "RSSI",
      "en": "RSSI"
    },
    "fingerprint": "sha256:6f41974074fcc77e8f964f9f9959b08859adafbfc5ab74c0d78cc14d33cacc5f",
    "aliases": {
      "legacy": "std:net.rssi",
      "short": "network.rssi"
    },
    "range": {
      "min": -200,
      "max": 0,
      "unit": "dB"
    },
    "description": {
      "ru": "Уровень принимаемого сигнала.",
      "en": "Received signal strength indicator."
    }
  },
  {
    "sid": "8d5c8d19",
    "path": "network.uptime",
    "kind": "quantity",
    "unit": "s",
    "encodings": [
      "i32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Аптайм",
      "en": "Uptime"
    },
    "fingerprint": "sha256:8d5c8d19e67f63ef729bb34f994f82fce0ce41e3656858ea2392e2585f3bd8c1",
    "aliases": {
      "legacy": "std:net.uptime",
      "short": "network.uptime"
    },
    "range": {
      "min": 0,
      "max": 1000000000000000,
      "unit": "s"
    },
    "description": {
      "ru": "Время непрерывной работы устройства в секундах.",
      "en": "Device continuous uptime in seconds."
    }
  },
  {
    "sid": "9744622b",
    "path": "physical.electrical.battery_soc",
    "kind": "quantity",
    "unit": "%",
    "encodings": [
      "f32",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Заряд батареи",
      "en": "Battery state of charge"
    },
    "fingerprint": "sha256:9744622b0c2efee235af3293ffaa73ac4d5237a8311874de01e296e7a663d159",
    "aliases": {
      "legacy": "std:elec.battery_soc",
      "short": "electrical.battery_soc"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Состояние заряда батареи в процентах.",
      "en": "Battery state of charge in percent."
    }
  },
  {
    "sid": "029cf91b",
    "path": "physical.electrical.current",
    "kind": "quantity",
    "unit": "A",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Ток",
      "en": "Current"
    },
    "fingerprint": "sha256:029cf91baaabee1d8bc7b9acd33a42f9cc5295807d9b3c690ab6cf781071f0e0",
    "aliases": {
      "legacy": "std:elec.current",
      "short": "electrical.current"
    },
    "range": {
      "min": -10000,
      "max": 10000,
      "unit": "A"
    },
    "description": {
      "ru": "Электрический ток.",
      "en": "Electrical current."
    }
  },
  {
    "sid": "81f1695e",
    "path": "physical.electrical.energy",
    "kind": "quantity",
    "unit": "Wh",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Энергия",
      "en": "Energy"
    },
    "fingerprint": "sha256:81f1695e4ef2ee330c7311142086c76b6bcd5235df6847b31e0861c75d15b0c0",
    "aliases": {
      "legacy": "std:elec.energy",
      "short": "electrical.energy"
    },
    "range": {
      "min": 0,
      "max": 1000000000000000,
      "unit": "Wh"
    },
    "description": {
      "ru": "Накопленная электрическая энергия.",
      "en": "Accumulated electrical energy."
    }
  },
  {
    "sid": "749128cc",
    "path": "physical.electrical.frequency",
    "kind": "quantity",
    "unit": "Hz",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Частота",
      "en": "Frequency"
    },
    "fingerprint": "sha256:749128cce644cb8ca4b4158dcc808eff26f8bbe2935ce0ccfb6edc20d56b5cfa",
    "aliases": {
      "legacy": "std:elec.frequency",
      "short": "electrical.frequency"
    },
    "range": {
      "min": 0,
      "max": 1000000000000,
      "unit": "Hz"
    },
    "description": {
      "ru": "Электрическая частота.",
      "en": "Electrical frequency."
    }
  },
  {
    "sid": "705c5b61",
    "path": "physical.electrical.power",
    "kind": "quantity",
    "unit": "W",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Мощность",
      "en": "Power"
    },
    "fingerprint": "sha256:705c5b61c9e9324bad2e1b4bc87468d78c27c06e1064bd581442b1b8a88214eb",
    "aliases": {
      "legacy": "std:elec.power",
      "short": "electrical.power"
    },
    "range": {
      "min": -1000000,
      "max": 1000000,
      "unit": "W"
    },
    "description": {
      "ru": "Электрическая мощность.",
      "en": "Electrical power."
    }
  },
  {
    "sid": "a4d3f616",
    "path": "physical.electrical.voltage",
    "kind": "quantity",
    "unit": "V",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Напряжение",
      "en": "Voltage"
    },
    "fingerprint": "sha256:a4d3f6163d84dd452f5bb296f29d0a8dff86b1163df0698f2ca7b832c406f66e",
    "aliases": {
      "legacy": "std:elec.voltage",
      "short": "electrical.voltage"
    },
    "range": {
      "min": -100000,
      "max": 100000,
      "unit": "V"
    },
    "description": {
      "ru": "Электрическое напряжение.",
      "en": "Electrical voltage."
    }
  },
  {
    "sid": "991ae51b",
    "path": "physical.environment.co2",
    "kind": "quantity",
    "unit": "ppm",
    "encodings": [
      "f32",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Концентрация CO2",
      "en": "CO2 concentration"
    },
    "fingerprint": "sha256:991ae51b291ca5d56a1c62780fee0236f008b61b22370f55f4708b87eb3f10b6",
    "aliases": {
      "legacy": "std:env.co2",
      "short": "environment.co2"
    },
    "range": {
      "min": 0,
      "max": 10000,
      "unit": "ppm"
    },
    "description": {
      "ru": "Концентрация углекислого газа в ppm.",
      "en": "Carbon dioxide concentration in ppm."
    }
  },
  {
    "sid": "94346493",
    "path": "physical.environment.humidity",
    "kind": "quantity",
    "unit": "%",
    "encodings": [
      "f32",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Относительная влажность",
      "en": "Relative humidity"
    },
    "fingerprint": "sha256:94346493b0fc7179cd3e271c7929060b44bbd77909a318421630cbdff9b7726a",
    "aliases": {
      "legacy": "std:env.humidity",
      "short": "environment.humidity"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Относительная влажность воздуха в процентах.",
      "en": "Relative air humidity in percent."
    }
  },
  {
    "sid": "f31fa92e",
    "path": "physical.environment.illuminance",
    "kind": "quantity",
    "unit": "lx",
    "encodings": [
      "f32",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Освещённость",
      "en": "Illuminance"
    },
    "fingerprint": "sha256:f31fa92e6cb910a36239a4df604d3f9aa5a30107c1fb15e86a6941da1e0c3a59",
    "aliases": {
      "legacy": "std:env.illuminance",
      "short": "environment.illuminance"
    },
    "range": {
      "min": 0,
      "max": 200000,
      "unit": "lx"
    },
    "description": {
      "ru": "Освещённость в люксах.",
      "en": "Illuminance in lux."
    }
  },
  {
    "sid": "bd0ff19a",
    "path": "physical.environment.pm25",
    "kind": "quantity",
    "unit": "ug/m3",
    "encodings": [
      "f32",
      "i16"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "PM2.5",
      "en": "PM2.5"
    },
    "fingerprint": "sha256:bd0ff19ac3c63ffb0714a4e39b45e1d6fbe418511d66940eafc6fc6899615e1a",
    "aliases": {
      "legacy": "std:env.pm25",
      "short": "environment.pm25"
    },
    "range": {
      "min": 0,
      "max": 1000,
      "unit": "ug/m3"
    },
    "description": {
      "ru": "Массовая концентрация частиц PM2.5.",
      "en": "PM2.5 particulate mass concentration."
    }
  },
  {
    "sid": "0d1c3212",
    "path": "physical.environment.pressure",
    "kind": "quantity",
    "unit": "hPa",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Атмосферное давление",
      "en": "Atmospheric pressure"
    },
    "fingerprint": "sha256:0d1c321207ab6d661db5cf54a835194f57458879a35a0dea4cab5ec6d50e998f",
    "aliases": {
      "legacy": "std:env.pressure",
      "short": "environment.pressure"
    },
    "range": {
      "min": 300,
      "max": 1100,
      "unit": "hPa"
    },
    "description": {
      "ru": "Барометрическое давление окружающей среды.",
      "en": "Ambient barometric pressure."
    }
  },
  {
    "sid": "24d3556f",
    "path": "physical.environment.temperature",
    "kind": "quantity",
    "unit": "Cel",
    "encodings": [
      "f32",
      "f64",
      "i16"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Температура",
      "en": "Temperature"
    },
    "fingerprint": "sha256:24d3556f189c9bbda772f6261516de963e623c12b6188e63d33ab3a8602e0b07",
    "aliases": {
      "legacy": "std:env.temperature",
      "short": "environment.temperature"
    },
    "range": {
      "min": -273.15,
      "max": 1000,
      "unit": "Cel"
    },
    "description": {
      "ru": "Температура окружающей среды или среды измерения.",
      "en": "Ambient or measured environment temperature."
    }
  },
  {
    "sid": "5ab774ed",
    "path": "physical.environment.voc",
    "kind": "quantity",
    "unit": "ppm",
    "encodings": [
      "f32",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "ЛОС / VOC",
      "en": "VOC"
    },
    "fingerprint": "sha256:5ab774ed1d798411de2477c4fa23212914fcd8ef8b1266f3c5f69a48ff447902",
    "aliases": {
      "legacy": "std:env.voc",
      "short": "environment.voc"
    },
    "range": {
      "min": 0,
      "max": 1000,
      "unit": "ppm"
    },
    "description": {
      "ru": "Концентрация летучих органических соединений.",
      "en": "Volatile organic compound concentration."
    }
  },
  {
    "sid": "d26a38e1",
    "path": "physical.geo.altitude",
    "kind": "quantity",
    "unit": "m",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Высота",
      "en": "Altitude"
    },
    "fingerprint": "sha256:d26a38e16b627173ae6920296c129a2fc84fe96930856901bded4747e692388d",
    "aliases": {
      "legacy": "std:geo.altitude",
      "short": "geo.altitude"
    },
    "range": {
      "min": -1000,
      "max": 100000,
      "unit": "m"
    },
    "description": {
      "ru": "Высота над уровнем моря или эллипсоидом.",
      "en": "Altitude above sea level or ellipsoid."
    }
  },
  {
    "sid": "4214c166",
    "path": "physical.geo.geopoint",
    "kind": "spatial",
    "unit": "-",
    "encodings": [
      "record"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Геоточка",
      "en": "Geopoint"
    },
    "fingerprint": "sha256:4214c1662e92cd0aa9a42860d5309baf8e9e0741cc574514c4a083c72278580e",
    "aliases": {
      "legacy": "std:geo.geopoint",
      "short": "geo.geopoint"
    },
    "description": {
      "ru": "Географическая точка: latitude, longitude (WGS84). Кодируется как record { lat, lon }.",
      "en": "Geographic point: latitude, longitude (WGS84). Encoded as record { lat, lon }."
    }
  },
  {
    "sid": "0abf6ccc",
    "path": "physical.geo.heading",
    "kind": "quantity",
    "unit": "deg",
    "encodings": [
      "f32",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Курс",
      "en": "Heading"
    },
    "fingerprint": "sha256:0abf6ccc5e1b02c2713212636397c9c441635817a929d22a63ab397e51dbcc8a",
    "aliases": {
      "legacy": "std:geo.heading",
      "short": "geo.heading"
    },
    "range": {
      "min": 0,
      "max": 360,
      "unit": "deg"
    },
    "description": {
      "ru": "Курс относительно севера в градусах.",
      "en": "Heading relative to north in degrees."
    }
  },
  {
    "sid": "1f1db238",
    "path": "physical.health.body_temp",
    "kind": "quantity",
    "unit": "Cel",
    "encodings": [
      "f32",
      "i16"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Температура тела",
      "en": "Body temperature"
    },
    "fingerprint": "sha256:1f1db2383382fe3f24c4ba8c1b9cf32bec2d360d2ae0cdf70ba528132d6871c2",
    "aliases": {
      "legacy": "std:health.body_temp",
      "short": "health.body_temp"
    },
    "range": {
      "min": 25,
      "max": 45,
      "unit": "Cel"
    },
    "description": {
      "ru": "Температура тела (потребительский тип).",
      "en": "Body temperature (consumer type)."
    }
  },
  {
    "sid": "7ec38c5b",
    "path": "physical.health.heart_rate",
    "kind": "quantity",
    "unit": "/min",
    "encodings": [
      "u8",
      "i16",
      "f32"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Частота пульса",
      "en": "Heart rate"
    },
    "fingerprint": "sha256:7ec38c5bd1e210dc811b969b1fc44d78eeeb4332799589d7584c5821a7245892",
    "aliases": {
      "legacy": "std:health.heart_rate",
      "short": "health.heart_rate"
    },
    "range": {
      "min": 0,
      "max": 300,
      "unit": "/min"
    },
    "description": {
      "ru": "Частота сердечных сокращений (потребительский тип, не медсертификация).",
      "en": "Heart rate (consumer type, not medical certification)."
    }
  },
  {
    "sid": "1d94ea87",
    "path": "physical.health.spo2",
    "kind": "quantity",
    "unit": "%",
    "encodings": [
      "u8",
      "f32"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "SpO2",
      "en": "SpO2"
    },
    "fingerprint": "sha256:1d94ea8784369f1fcc5d4f4a7d3bd173f145e0fd544db5962a7434cc07772b21",
    "aliases": {
      "legacy": "std:health.spo2",
      "short": "health.spo2"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Насыщение крови кислородом (потребительский тип).",
      "en": "Blood oxygen saturation (consumer type)."
    }
  },
  {
    "sid": "67b72924",
    "path": "physical.mechanical.flow",
    "kind": "quantity",
    "unit": "L/min",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Расход",
      "en": "Flow rate"
    },
    "fingerprint": "sha256:67b72924e7db7a4407062135341550b670d7f9db9927e08acd95c1e367ab53e9",
    "aliases": {
      "legacy": "std:mech.flow",
      "short": "mechanical.flow"
    },
    "range": {
      "min": 0,
      "max": 1000000,
      "unit": "L/min"
    },
    "description": {
      "ru": "Объёмный расход жидкости или газа.",
      "en": "Volumetric flow rate of fluid or gas."
    }
  },
  {
    "sid": "d38e7705",
    "path": "physical.mechanical.force",
    "kind": "quantity",
    "unit": "N",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Сила",
      "en": "Force"
    },
    "fingerprint": "sha256:d38e7705f19ae4381e4ac485fb5f0cd12dcdec120300b19ab2e9820f9f1e6c5c",
    "aliases": {
      "legacy": "std:mech.force",
      "short": "mechanical.force"
    },
    "range": {
      "min": -1000000000,
      "max": 1000000000,
      "unit": "N"
    },
    "description": {
      "ru": "Механическая сила.",
      "en": "Mechanical force."
    }
  },
  {
    "sid": "b0209dc2",
    "path": "physical.mechanical.pressure_gauge",
    "kind": "quantity",
    "unit": "Pa",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Манометрическое давление",
      "en": "Gauge pressure"
    },
    "fingerprint": "sha256:b0209dc2c9184836f41626063ea44b433902e40d799ca84c97e4a73f275cead1",
    "aliases": {
      "legacy": "std:mech.pressure_gauge",
      "short": "mechanical.pressure_gauge"
    },
    "range": {
      "min": -100000000,
      "max": 1000000000,
      "unit": "Pa"
    },
    "description": {
      "ru": "Давление в механической / технологической системе.",
      "en": "Pressure in a mechanical or process system."
    }
  },
  {
    "sid": "8c138cb4",
    "path": "physical.mechanical.torque",
    "kind": "quantity",
    "unit": "N.m",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Крутящий момент",
      "en": "Torque"
    },
    "fingerprint": "sha256:8c138cb42a5edc7e8104f47d37a0ecefba487e51d254bc2c143f4669f46768f0",
    "aliases": {
      "legacy": "std:mech.torque",
      "short": "mechanical.torque"
    },
    "range": {
      "min": -1000000000,
      "max": 1000000000,
      "unit": "N.m"
    },
    "description": {
      "ru": "Крутящий момент.",
      "en": "Mechanical torque."
    }
  },
  {
    "sid": "c0154acf",
    "path": "physical.motion.acceleration",
    "kind": "quantity",
    "unit": "m/s2",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Ускорение",
      "en": "Acceleration"
    },
    "fingerprint": "sha256:c0154acf370a04a4fd690a526380759018e61677f83513ec9a61f6bd163f991f",
    "aliases": {
      "legacy": "std:motion.acceleration",
      "short": "motion.acceleration"
    },
    "range": {
      "min": -1000000,
      "max": 1000000,
      "unit": "m/s2"
    },
    "description": {
      "ru": "Линейное ускорение.",
      "en": "Linear acceleration."
    }
  },
  {
    "sid": "99e3d569",
    "path": "physical.motion.position",
    "kind": "quantity",
    "unit": "m",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Позиция",
      "en": "Position"
    },
    "fingerprint": "sha256:99e3d5695e4ba1b52bb4b202836f36fb8826d728a83ece15d531cb93203988e8",
    "aliases": {
      "legacy": "std:motion.position",
      "short": "motion.position"
    },
    "range": {
      "min": -1000000000,
      "max": 1000000000,
      "unit": "m"
    },
    "description": {
      "ru": "Линейное положение по оси (локальная система).",
      "en": "Linear position along an axis (local frame)."
    }
  },
  {
    "sid": "993c1f96",
    "path": "physical.motion.rotation",
    "kind": "quantity",
    "unit": "deg",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Угол поворота",
      "en": "Rotation"
    },
    "fingerprint": "sha256:993c1f9667a98ed2d444a34c3e64a5237139aff207232b3bf1da176f139cdd85",
    "aliases": {
      "legacy": "std:motion.rotation",
      "short": "motion.rotation"
    },
    "range": {
      "min": -3600,
      "max": 3600,
      "unit": "deg"
    },
    "description": {
      "ru": "Угол поворота в градусах.",
      "en": "Rotation angle in degrees."
    }
  },
  {
    "sid": "59be49ea",
    "path": "physical.motion.velocity",
    "kind": "quantity",
    "unit": "m/s",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Скорость",
      "en": "Velocity"
    },
    "fingerprint": "sha256:59be49ea71339153700e970b26b62c1b17f55bd027ca9b830da7a6cf6e9cc42f",
    "aliases": {
      "legacy": "std:motion.velocity",
      "short": "motion.velocity"
    },
    "range": {
      "min": -1000000,
      "max": 1000000,
      "unit": "m/s"
    },
    "description": {
      "ru": "Линейная скорость.",
      "en": "Linear velocity."
    }
  },
  {
    "sid": "fb2badbe",
    "path": "temporal.duration",
    "kind": "temporal",
    "unit": "s",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Длительность",
      "en": "Duration"
    },
    "fingerprint": "sha256:fb2badbef8d8563b8528261739ef62f81b148013c95fdd8599bb7a94b35152c1",
    "aliases": {
      "legacy": "std:time.duration",
      "short": "temporal.duration"
    },
    "range": {
      "min": 0,
      "max": 1000000000000000,
      "unit": "s"
    },
    "description": {
      "ru": "Длительность интервала в секундах.",
      "en": "Interval duration in seconds."
    }
  },
  {
    "sid": "f0af635e",
    "path": "temporal.timestamp",
    "kind": "temporal",
    "unit": "s",
    "encodings": [
      "i32",
      "f64",
      "utf8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Метка времени",
      "en": "Timestamp"
    },
    "fingerprint": "sha256:f0af635e43278f4549e7d8b7d378b3ef92d21cd8f1547db606844151e9a5a41b",
    "aliases": {
      "legacy": "std:time.timestamp",
      "short": "temporal.timestamp"
    },
    "description": {
      "ru": "Момент времени (Unix seconds или ISO-8601 в utf8).",
      "en": "Point in time (Unix seconds or ISO-8601 as utf8)."
    }
  }
] as const;

export const PROFILES: readonly StandartProfile[] = [
  {
    "id": "actuator",
    "version": "0.2.0",
    "title": {
      "ru": "Исполнительный механизм",
      "en": "Actuator"
    },
    "description": {
      "ru": "Устройство, принимающее команды и сообщающее состояние.",
      "en": "Device that accepts commands and reports state."
    },
    "required": [
      "84ca530f",
      "3d53bc7d"
    ],
    "optional": [
      "069b2a4c",
      "faa74c01",
      "e34550dd",
      "653381be",
      "f0af635e",
      "8d5c8d19"
    ]
  },
  {
    "id": "gps",
    "version": "0.2.0",
    "title": {
      "ru": "GPS / GNSS трекер",
      "en": "GPS / GNSS tracker"
    },
    "description": {
      "ru": "Устройство геопозиционирования.",
      "en": "Geopositioning device."
    },
    "required": [
      "4214c166",
      "3d53bc7d"
    ],
    "optional": [
      "d26a38e1",
      "0abf6ccc",
      "59be49ea",
      "f0af635e",
      "9744622b",
      "6f419740"
    ]
  },
  {
    "id": "meter",
    "version": "0.2.0",
    "title": {
      "ru": "Электросчётчик / измеритель",
      "en": "Electrical meter"
    },
    "description": {
      "ru": "Устройство измерения электрических величин.",
      "en": "Device measuring electrical quantities."
    },
    "required": [
      "a4d3f616",
      "029cf91b",
      "705c5b61",
      "3d53bc7d"
    ],
    "optional": [
      "81f1695e",
      "749128cc",
      "f0af635e",
      "8d5c8d19"
    ]
  },
  {
    "id": "thermometer",
    "version": "0.2.0",
    "title": {
      "ru": "Термометр",
      "en": "Thermometer"
    },
    "description": {
      "ru": "Устройство, измеряющее температуру окружающей среды.",
      "en": "Device measuring ambient temperature."
    },
    "required": [
      "24d3556f",
      "3d53bc7d"
    ],
    "optional": [
      "94346493",
      "f0af635e",
      "9744622b",
      "6f419740"
    ]
  }
] as const;

export function getBySid(sid: string): StandartTypeCard | undefined {
  return TYPES.find((t) => t.sid === sid);
}

export function getByPath(path: string): StandartTypeCard | undefined {
  return TYPES.find((t) => t.path === path);
}

export function getProfile(id: StandartProfileId): StandartProfile | undefined {
  return PROFILES.find((p) => p.id === id);
}

export function isSid(value: string): value is StandartSid {
  return TYPES.some((t) => t.sid === value);
}
