/* Generated by tools/codegen.mjs — do not edit by hand. */
/* SPDX-License-Identifier: Apache-2.0 */

export const STANDART_REGISTRY_VERSION = "0.1.0" as const;

export type StandartTypeId =
  | "std:act.command"
  | "std:act.power"
  | "std:act.setpoint"
  | "std:elec.battery_soc"
  | "std:elec.current"
  | "std:elec.energy"
  | "std:elec.frequency"
  | "std:elec.power"
  | "std:elec.voltage"
  | "std:env.co2"
  | "std:env.humidity"
  | "std:env.illuminance"
  | "std:env.pm25"
  | "std:env.pressure"
  | "std:env.temperature"
  | "std:env.voc"
  | "std:geo.altitude"
  | "std:geo.geopoint"
  | "std:geo.heading"
  | "std:health.body_temp"
  | "std:health.heart_rate"
  | "std:health.spo2"
  | "std:id.device"
  | "std:id.mac"
  | "std:id.serial"
  | "std:id.uuid"
  | "std:logical.flag"
  | "std:logical.level"
  | "std:logical.mode"
  | "std:mech.flow"
  | "std:mech.force"
  | "std:mech.pressure_gauge"
  | "std:mech.torque"
  | "std:media.audio_ref"
  | "std:media.image_ref"
  | "std:motion.acceleration"
  | "std:motion.position"
  | "std:motion.rotation"
  | "std:motion.velocity"
  | "std:net.rssi"
  | "std:net.uptime"
  | "std:time.duration"
  | "std:time.timestamp";

export type StandartProfileId =
  | "actuator"
  | "gps"
  | "meter"
  | "thermometer";

export type StandartKind =
  | "quantity"
  | "enum"
  | "identity"
  | "temporal"
  | "spatial"
  | "logical"
  | "media"
  | "structured"
  | "event"
  | "command";

export type StandartEncoding =
  | "bool"
  | "u8"
  | "i16"
  | "i32"
  | "f32"
  | "f64"
  | "utf8"
  | "bytes"
  | "record"
  | "enum";

export type StandartSensitivity = "public" | "internal" | "personal" | "restricted";
export type StandartStatus = "stable" | "draft" | "deprecated";

export interface LocalizedString {
  ru: string;
  en: string;
}

export interface StandartTypeCard {
  id: StandartTypeId;
  kind: StandartKind;
  domain: string;
  defaultUnit: string;
  encodings: StandartEncoding[];
  sensitivity: StandartSensitivity;
  status: StandartStatus;
  title: LocalizedString;
  description?: LocalizedString;
  range?: { min: number; max: number; unit: string };
  enumValues?: string[];
}

export interface StandartProfile {
  id: StandartProfileId;
  version: string;
  title: LocalizedString;
  description?: LocalizedString;
  required: StandartTypeId[];
  optional: StandartTypeId[];
}

export interface StandartReading {
  type: StandartTypeId;
  unit: string;
  enc: StandartEncoding;
  v: unknown;
  t?: number;
}

export const TypeId = {
  ACT_COMMAND: "std:act.command" as const,
  ACT_POWER: "std:act.power" as const,
  ACT_SETPOINT: "std:act.setpoint" as const,
  ELEC_BATTERY_SOC: "std:elec.battery_soc" as const,
  ELEC_CURRENT: "std:elec.current" as const,
  ELEC_ENERGY: "std:elec.energy" as const,
  ELEC_FREQUENCY: "std:elec.frequency" as const,
  ELEC_POWER: "std:elec.power" as const,
  ELEC_VOLTAGE: "std:elec.voltage" as const,
  ENV_CO2: "std:env.co2" as const,
  ENV_HUMIDITY: "std:env.humidity" as const,
  ENV_ILLUMINANCE: "std:env.illuminance" as const,
  ENV_PM25: "std:env.pm25" as const,
  ENV_PRESSURE: "std:env.pressure" as const,
  ENV_TEMPERATURE: "std:env.temperature" as const,
  ENV_VOC: "std:env.voc" as const,
  GEO_ALTITUDE: "std:geo.altitude" as const,
  GEO_GEOPOINT: "std:geo.geopoint" as const,
  GEO_HEADING: "std:geo.heading" as const,
  HEALTH_BODY_TEMP: "std:health.body_temp" as const,
  HEALTH_HEART_RATE: "std:health.heart_rate" as const,
  HEALTH_SPO2: "std:health.spo2" as const,
  ID_DEVICE: "std:id.device" as const,
  ID_MAC: "std:id.mac" as const,
  ID_SERIAL: "std:id.serial" as const,
  ID_UUID: "std:id.uuid" as const,
  LOGICAL_FLAG: "std:logical.flag" as const,
  LOGICAL_LEVEL: "std:logical.level" as const,
  LOGICAL_MODE: "std:logical.mode" as const,
  MECH_FLOW: "std:mech.flow" as const,
  MECH_FORCE: "std:mech.force" as const,
  MECH_PRESSURE_GAUGE: "std:mech.pressure_gauge" as const,
  MECH_TORQUE: "std:mech.torque" as const,
  MEDIA_AUDIO_REF: "std:media.audio_ref" as const,
  MEDIA_IMAGE_REF: "std:media.image_ref" as const,
  MOTION_ACCELERATION: "std:motion.acceleration" as const,
  MOTION_POSITION: "std:motion.position" as const,
  MOTION_ROTATION: "std:motion.rotation" as const,
  MOTION_VELOCITY: "std:motion.velocity" as const,
  NET_RSSI: "std:net.rssi" as const,
  NET_UPTIME: "std:net.uptime" as const,
  TIME_DURATION: "std:time.duration" as const,
  TIME_TIMESTAMP: "std:time.timestamp" as const,
} as const;

export const TYPES: readonly StandartTypeCard[] = [
  {
    "id": "std:act.command",
    "kind": "command",
    "domain": "act",
    "defaultUnit": "-",
    "encodings": [
      "enum",
      "utf8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Команда",
      "en": "Command"
    },
    "enumValues": [
      "start",
      "stop",
      "reset",
      "open",
      "close",
      "toggle"
    ],
    "description": {
      "ru": "Команда воздействия на исполнительный механизм.",
      "en": "Actuation command for an actuator."
    }
  },
  {
    "id": "std:act.power",
    "kind": "enum",
    "domain": "act",
    "defaultUnit": "-",
    "encodings": [
      "enum",
      "bool"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Питание / включение",
      "en": "Power on/off"
    },
    "enumValues": [
      "off",
      "on"
    ],
    "description": {
      "ru": "Состояние питания или включения актуатора.",
      "en": "Power or actuator on/off state."
    }
  },
  {
    "id": "std:act.setpoint",
    "kind": "quantity",
    "domain": "act",
    "defaultUnit": "-",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Уставка",
      "en": "Setpoint"
    },
    "description": {
      "ru": "Целевое значение для регулятора; единица уточняется приложением или профилем.",
      "en": "Target value for a controller; unit is application- or profile-specific."
    }
  },
  {
    "id": "std:elec.battery_soc",
    "kind": "quantity",
    "domain": "elec",
    "defaultUnit": "%",
    "encodings": [
      "f32",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Заряд батареи",
      "en": "Battery state of charge"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Состояние заряда батареи в процентах.",
      "en": "Battery state of charge in percent."
    }
  },
  {
    "id": "std:elec.current",
    "kind": "quantity",
    "domain": "elec",
    "defaultUnit": "A",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Ток",
      "en": "Current"
    },
    "range": {
      "min": -10000,
      "max": 10000,
      "unit": "A"
    },
    "description": {
      "ru": "Электрический ток.",
      "en": "Electrical current."
    }
  },
  {
    "id": "std:elec.energy",
    "kind": "quantity",
    "domain": "elec",
    "defaultUnit": "Wh",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Энергия",
      "en": "Energy"
    },
    "range": {
      "min": 0,
      "max": 1000000000000000,
      "unit": "Wh"
    },
    "description": {
      "ru": "Накопленная электрическая энергия.",
      "en": "Accumulated electrical energy."
    }
  },
  {
    "id": "std:elec.frequency",
    "kind": "quantity",
    "domain": "elec",
    "defaultUnit": "Hz",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Частота",
      "en": "Frequency"
    },
    "range": {
      "min": 0,
      "max": 1000000000000,
      "unit": "Hz"
    },
    "description": {
      "ru": "Электрическая частота.",
      "en": "Electrical frequency."
    }
  },
  {
    "id": "std:elec.power",
    "kind": "quantity",
    "domain": "elec",
    "defaultUnit": "W",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Мощность",
      "en": "Power"
    },
    "range": {
      "min": -1000000,
      "max": 1000000,
      "unit": "W"
    },
    "description": {
      "ru": "Электрическая мощность.",
      "en": "Electrical power."
    }
  },
  {
    "id": "std:elec.voltage",
    "kind": "quantity",
    "domain": "elec",
    "defaultUnit": "V",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Напряжение",
      "en": "Voltage"
    },
    "range": {
      "min": -100000,
      "max": 100000,
      "unit": "V"
    },
    "description": {
      "ru": "Электрическое напряжение.",
      "en": "Electrical voltage."
    }
  },
  {
    "id": "std:env.co2",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "ppm",
    "encodings": [
      "f32",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Концентрация CO2",
      "en": "CO2 concentration"
    },
    "range": {
      "min": 0,
      "max": 10000,
      "unit": "ppm"
    },
    "description": {
      "ru": "Концентрация углекислого газа в ppm.",
      "en": "Carbon dioxide concentration in ppm."
    }
  },
  {
    "id": "std:env.humidity",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "%",
    "encodings": [
      "f32",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Относительная влажность",
      "en": "Relative humidity"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Относительная влажность воздуха в процентах.",
      "en": "Relative air humidity in percent."
    }
  },
  {
    "id": "std:env.illuminance",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "lx",
    "encodings": [
      "f32",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Освещённость",
      "en": "Illuminance"
    },
    "range": {
      "min": 0,
      "max": 200000,
      "unit": "lx"
    },
    "description": {
      "ru": "Освещённость в люксах.",
      "en": "Illuminance in lux."
    }
  },
  {
    "id": "std:env.pm25",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "ug/m3",
    "encodings": [
      "f32",
      "i16"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "PM2.5",
      "en": "PM2.5"
    },
    "range": {
      "min": 0,
      "max": 1000,
      "unit": "ug/m3"
    },
    "description": {
      "ru": "Массовая концентрация частиц PM2.5.",
      "en": "PM2.5 particulate mass concentration."
    }
  },
  {
    "id": "std:env.pressure",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "hPa",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Атмосферное давление",
      "en": "Atmospheric pressure"
    },
    "range": {
      "min": 300,
      "max": 1100,
      "unit": "hPa"
    },
    "description": {
      "ru": "Барометрическое давление окружающей среды.",
      "en": "Ambient barometric pressure."
    }
  },
  {
    "id": "std:env.temperature",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "Cel",
    "encodings": [
      "f32",
      "f64",
      "i16"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Температура",
      "en": "Temperature"
    },
    "range": {
      "min": -273.15,
      "max": 1000,
      "unit": "Cel"
    },
    "description": {
      "ru": "Температура окружающей среды или среды измерения.",
      "en": "Ambient or measured environment temperature."
    }
  },
  {
    "id": "std:env.voc",
    "kind": "quantity",
    "domain": "env",
    "defaultUnit": "ppm",
    "encodings": [
      "f32",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "ЛОС / VOC",
      "en": "VOC"
    },
    "range": {
      "min": 0,
      "max": 1000,
      "unit": "ppm"
    },
    "description": {
      "ru": "Концентрация летучих органических соединений.",
      "en": "Volatile organic compound concentration."
    }
  },
  {
    "id": "std:geo.altitude",
    "kind": "quantity",
    "domain": "geo",
    "defaultUnit": "m",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Высота",
      "en": "Altitude"
    },
    "range": {
      "min": -1000,
      "max": 100000,
      "unit": "m"
    },
    "description": {
      "ru": "Высота над уровнем моря или эллипсоидом.",
      "en": "Altitude above sea level or ellipsoid."
    }
  },
  {
    "id": "std:geo.geopoint",
    "kind": "spatial",
    "domain": "geo",
    "defaultUnit": "-",
    "encodings": [
      "record"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Геоточка",
      "en": "Geopoint"
    },
    "description": {
      "ru": "Географическая точка: latitude, longitude (WGS84). Кодируется как record { lat, lon }.",
      "en": "Geographic point: latitude, longitude (WGS84). Encoded as record { lat, lon }."
    }
  },
  {
    "id": "std:geo.heading",
    "kind": "quantity",
    "domain": "geo",
    "defaultUnit": "deg",
    "encodings": [
      "f32",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Курс",
      "en": "Heading"
    },
    "range": {
      "min": 0,
      "max": 360,
      "unit": "deg"
    },
    "description": {
      "ru": "Курс относительно севера в градусах.",
      "en": "Heading relative to north in degrees."
    }
  },
  {
    "id": "std:health.body_temp",
    "kind": "quantity",
    "domain": "health",
    "defaultUnit": "Cel",
    "encodings": [
      "f32",
      "i16"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Температура тела",
      "en": "Body temperature"
    },
    "range": {
      "min": 25,
      "max": 45,
      "unit": "Cel"
    },
    "description": {
      "ru": "Температура тела (потребительский тип).",
      "en": "Body temperature (consumer type)."
    }
  },
  {
    "id": "std:health.heart_rate",
    "kind": "quantity",
    "domain": "health",
    "defaultUnit": "/min",
    "encodings": [
      "u8",
      "i16",
      "f32"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "Частота пульса",
      "en": "Heart rate"
    },
    "range": {
      "min": 0,
      "max": 300,
      "unit": "/min"
    },
    "description": {
      "ru": "Частота сердечных сокращений (потребительский тип, не медсертификация).",
      "en": "Heart rate (consumer type, not medical certification)."
    }
  },
  {
    "id": "std:health.spo2",
    "kind": "quantity",
    "domain": "health",
    "defaultUnit": "%",
    "encodings": [
      "u8",
      "f32"
    ],
    "sensitivity": "personal",
    "status": "stable",
    "title": {
      "ru": "SpO2",
      "en": "SpO2"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Насыщение крови кислородом (потребительский тип).",
      "en": "Blood oxygen saturation (consumer type)."
    }
  },
  {
    "id": "std:id.device",
    "kind": "identity",
    "domain": "id",
    "defaultUnit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Идентификатор устройства",
      "en": "Device identifier"
    },
    "description": {
      "ru": "Стабильный идентификатор устройства (рекомендуется urn:std:id:dev:...).",
      "en": "Stable device identifier (recommended urn:std:id:dev:...)."
    }
  },
  {
    "id": "std:id.mac",
    "kind": "identity",
    "domain": "id",
    "defaultUnit": "-",
    "encodings": [
      "utf8",
      "bytes"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "MAC-адрес",
      "en": "MAC address"
    },
    "description": {
      "ru": "Аппаратный MAC-адрес (строка или 6 байт).",
      "en": "Hardware MAC address (string or 6 bytes)."
    }
  },
  {
    "id": "std:id.serial",
    "kind": "identity",
    "domain": "id",
    "defaultUnit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Серийный номер",
      "en": "Serial number"
    },
    "description": {
      "ru": "Серийный номер производителя.",
      "en": "Manufacturer serial number."
    }
  },
  {
    "id": "std:id.uuid",
    "kind": "identity",
    "domain": "id",
    "defaultUnit": "-",
    "encodings": [
      "utf8",
      "bytes"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "UUID",
      "en": "UUID"
    },
    "description": {
      "ru": "Универсальный уникальный идентификатор (строка или 16 байт).",
      "en": "Universally unique identifier (string or 16 bytes)."
    }
  },
  {
    "id": "std:logical.flag",
    "kind": "logical",
    "domain": "logical",
    "defaultUnit": "-",
    "encodings": [
      "bool",
      "u8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Флаг",
      "en": "Flag"
    },
    "description": {
      "ru": "Логический флаг true/false.",
      "en": "Boolean flag true/false."
    }
  },
  {
    "id": "std:logical.level",
    "kind": "quantity",
    "domain": "logical",
    "defaultUnit": "%",
    "encodings": [
      "u8",
      "f32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Уровень",
      "en": "Level"
    },
    "range": {
      "min": 0,
      "max": 100,
      "unit": "%"
    },
    "description": {
      "ru": "Нормированный уровень 0–100%.",
      "en": "Normalized level 0–100%."
    }
  },
  {
    "id": "std:logical.mode",
    "kind": "enum",
    "domain": "logical",
    "defaultUnit": "-",
    "encodings": [
      "enum",
      "utf8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Режим",
      "en": "Mode"
    },
    "enumValues": [
      "off",
      "on",
      "auto",
      "sleep",
      "error"
    ],
    "description": {
      "ru": "Общий режим работы устройства.",
      "en": "Generic device operating mode."
    }
  },
  {
    "id": "std:mech.flow",
    "kind": "quantity",
    "domain": "mech",
    "defaultUnit": "L/min",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Расход",
      "en": "Flow rate"
    },
    "range": {
      "min": 0,
      "max": 1000000,
      "unit": "L/min"
    },
    "description": {
      "ru": "Объёмный расход жидкости или газа.",
      "en": "Volumetric flow rate of fluid or gas."
    }
  },
  {
    "id": "std:mech.force",
    "kind": "quantity",
    "domain": "mech",
    "defaultUnit": "N",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Сила",
      "en": "Force"
    },
    "range": {
      "min": -1000000000,
      "max": 1000000000,
      "unit": "N"
    },
    "description": {
      "ru": "Механическая сила.",
      "en": "Mechanical force."
    }
  },
  {
    "id": "std:mech.pressure_gauge",
    "kind": "quantity",
    "domain": "mech",
    "defaultUnit": "Pa",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Манометрическое давление",
      "en": "Gauge pressure"
    },
    "range": {
      "min": -100000000,
      "max": 1000000000,
      "unit": "Pa"
    },
    "description": {
      "ru": "Давление в механической / технологической системе.",
      "en": "Pressure in a mechanical or process system."
    }
  },
  {
    "id": "std:mech.torque",
    "kind": "quantity",
    "domain": "mech",
    "defaultUnit": "N.m",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Крутящий момент",
      "en": "Torque"
    },
    "range": {
      "min": -1000000000,
      "max": 1000000000,
      "unit": "N.m"
    },
    "description": {
      "ru": "Крутящий момент.",
      "en": "Mechanical torque."
    }
  },
  {
    "id": "std:media.audio_ref",
    "kind": "media",
    "domain": "media",
    "defaultUnit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Ссылка на аудио",
      "en": "Audio reference"
    },
    "description": {
      "ru": "URI или путь к аудиофайлу.",
      "en": "URI or path to an audio resource."
    }
  },
  {
    "id": "std:media.image_ref",
    "kind": "media",
    "domain": "media",
    "defaultUnit": "-",
    "encodings": [
      "utf8"
    ],
    "sensitivity": "internal",
    "status": "stable",
    "title": {
      "ru": "Ссылка на изображение",
      "en": "Image reference"
    },
    "description": {
      "ru": "URI или путь к изображению.",
      "en": "URI or path to an image."
    }
  },
  {
    "id": "std:motion.acceleration",
    "kind": "quantity",
    "domain": "motion",
    "defaultUnit": "m/s2",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Ускорение",
      "en": "Acceleration"
    },
    "range": {
      "min": -1000000,
      "max": 1000000,
      "unit": "m/s2"
    },
    "description": {
      "ru": "Линейное ускорение.",
      "en": "Linear acceleration."
    }
  },
  {
    "id": "std:motion.position",
    "kind": "quantity",
    "domain": "motion",
    "defaultUnit": "m",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Позиция",
      "en": "Position"
    },
    "range": {
      "min": -1000000000,
      "max": 1000000000,
      "unit": "m"
    },
    "description": {
      "ru": "Линейное положение по оси (локальная система).",
      "en": "Linear position along an axis (local frame)."
    }
  },
  {
    "id": "std:motion.rotation",
    "kind": "quantity",
    "domain": "motion",
    "defaultUnit": "deg",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Угол поворота",
      "en": "Rotation"
    },
    "range": {
      "min": -3600,
      "max": 3600,
      "unit": "deg"
    },
    "description": {
      "ru": "Угол поворота в градусах.",
      "en": "Rotation angle in degrees."
    }
  },
  {
    "id": "std:motion.velocity",
    "kind": "quantity",
    "domain": "motion",
    "defaultUnit": "m/s",
    "encodings": [
      "f32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Скорость",
      "en": "Velocity"
    },
    "range": {
      "min": -1000000,
      "max": 1000000,
      "unit": "m/s"
    },
    "description": {
      "ru": "Линейная скорость.",
      "en": "Linear velocity."
    }
  },
  {
    "id": "std:net.rssi",
    "kind": "quantity",
    "domain": "net",
    "defaultUnit": "dB",
    "encodings": [
      "i16",
      "f32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "RSSI",
      "en": "RSSI"
    },
    "range": {
      "min": -200,
      "max": 0,
      "unit": "dB"
    },
    "description": {
      "ru": "Уровень принимаемого сигнала.",
      "en": "Received signal strength indicator."
    }
  },
  {
    "id": "std:net.uptime",
    "kind": "quantity",
    "domain": "net",
    "defaultUnit": "s",
    "encodings": [
      "i32",
      "f64"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Аптайм",
      "en": "Uptime"
    },
    "range": {
      "min": 0,
      "max": 1000000000000000,
      "unit": "s"
    },
    "description": {
      "ru": "Время непрерывной работы устройства в секундах.",
      "en": "Device continuous uptime in seconds."
    }
  },
  {
    "id": "std:time.duration",
    "kind": "temporal",
    "domain": "time",
    "defaultUnit": "s",
    "encodings": [
      "f32",
      "f64",
      "i32"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Длительность",
      "en": "Duration"
    },
    "range": {
      "min": 0,
      "max": 1000000000000000,
      "unit": "s"
    },
    "description": {
      "ru": "Длительность интервала в секундах.",
      "en": "Interval duration in seconds."
    }
  },
  {
    "id": "std:time.timestamp",
    "kind": "temporal",
    "domain": "time",
    "defaultUnit": "s",
    "encodings": [
      "i32",
      "f64",
      "utf8"
    ],
    "sensitivity": "public",
    "status": "stable",
    "title": {
      "ru": "Метка времени",
      "en": "Timestamp"
    },
    "description": {
      "ru": "Момент времени (Unix seconds или ISO-8601 в utf8).",
      "en": "Point in time (Unix seconds or ISO-8601 as utf8)."
    }
  }
] as const;

export const PROFILES: readonly StandartProfile[] = [
  {
    "id": "actuator",
    "version": "0.1.0",
    "title": {
      "ru": "Исполнительный механизм",
      "en": "Actuator"
    },
    "description": {
      "ru": "Устройство, принимающее команды и сообщающее состояние.",
      "en": "Device that accepts commands and reports state."
    },
    "required": [
      "std:act.power",
      "std:id.device"
    ],
    "optional": [
      "std:act.command",
      "std:act.setpoint",
      "std:logical.mode",
      "std:logical.level",
      "std:time.timestamp",
      "std:net.uptime"
    ]
  },
  {
    "id": "gps",
    "version": "0.1.0",
    "title": {
      "ru": "GPS / GNSS трекер",
      "en": "GPS / GNSS tracker"
    },
    "description": {
      "ru": "Устройство геопозиционирования.",
      "en": "Geopositioning device."
    },
    "required": [
      "std:geo.geopoint",
      "std:id.device"
    ],
    "optional": [
      "std:geo.altitude",
      "std:geo.heading",
      "std:motion.velocity",
      "std:time.timestamp",
      "std:elec.battery_soc",
      "std:net.rssi"
    ]
  },
  {
    "id": "meter",
    "version": "0.1.0",
    "title": {
      "ru": "Электросчётчик / измеритель",
      "en": "Electrical meter"
    },
    "description": {
      "ru": "Устройство измерения электрических величин.",
      "en": "Device measuring electrical quantities."
    },
    "required": [
      "std:elec.voltage",
      "std:elec.current",
      "std:elec.power",
      "std:id.device"
    ],
    "optional": [
      "std:elec.energy",
      "std:elec.frequency",
      "std:time.timestamp",
      "std:net.uptime"
    ]
  },
  {
    "id": "thermometer",
    "version": "0.1.0",
    "title": {
      "ru": "Термометр",
      "en": "Thermometer"
    },
    "description": {
      "ru": "Устройство, измеряющее температуру окружающей среды.",
      "en": "Device measuring ambient temperature."
    },
    "required": [
      "std:env.temperature",
      "std:id.device"
    ],
    "optional": [
      "std:env.humidity",
      "std:time.timestamp",
      "std:elec.battery_soc",
      "std:net.rssi"
    ]
  }
] as const;

export function getType(id: StandartTypeId): StandartTypeCard | undefined {
  return TYPES.find((t) => t.id === id);
}

export function getProfile(id: StandartProfileId): StandartProfile | undefined {
  return PROFILES.find((p) => p.id === id);
}

export function isTypeId(value: string): value is StandartTypeId {
  return TYPES.some((t) => t.id === value);
}
