/* Generated by tools/codegen.mjs — do not edit by hand. */
/* SPDX-License-Identifier: Apache-2.0 */
#ifndef STANDART_H
#define STANDART_H

#define STANDART_REGISTRY_VERSION "0.1.0"
#define STANDART_TYPE_COUNT 43
#define STANDART_PROFILE_COUNT 4

/* Type identifiers */
#define STD_ACT_COMMAND "std:act.command"
#define STD_ACT_POWER "std:act.power"
#define STD_ACT_SETPOINT "std:act.setpoint"
#define STD_ELEC_BATTERY_SOC "std:elec.battery_soc"
#define STD_ELEC_CURRENT "std:elec.current"
#define STD_ELEC_ENERGY "std:elec.energy"
#define STD_ELEC_FREQUENCY "std:elec.frequency"
#define STD_ELEC_POWER "std:elec.power"
#define STD_ELEC_VOLTAGE "std:elec.voltage"
#define STD_ENV_CO2 "std:env.co2"
#define STD_ENV_HUMIDITY "std:env.humidity"
#define STD_ENV_ILLUMINANCE "std:env.illuminance"
#define STD_ENV_PM25 "std:env.pm25"
#define STD_ENV_PRESSURE "std:env.pressure"
#define STD_ENV_TEMPERATURE "std:env.temperature"
#define STD_ENV_VOC "std:env.voc"
#define STD_GEO_ALTITUDE "std:geo.altitude"
#define STD_GEO_GEOPOINT "std:geo.geopoint"
#define STD_GEO_HEADING "std:geo.heading"
#define STD_HEALTH_BODY_TEMP "std:health.body_temp"
#define STD_HEALTH_HEART_RATE "std:health.heart_rate"
#define STD_HEALTH_SPO2 "std:health.spo2"
#define STD_ID_DEVICE "std:id.device"
#define STD_ID_MAC "std:id.mac"
#define STD_ID_SERIAL "std:id.serial"
#define STD_ID_UUID "std:id.uuid"
#define STD_LOGICAL_FLAG "std:logical.flag"
#define STD_LOGICAL_LEVEL "std:logical.level"
#define STD_LOGICAL_MODE "std:logical.mode"
#define STD_MECH_FLOW "std:mech.flow"
#define STD_MECH_FORCE "std:mech.force"
#define STD_MECH_PRESSURE_GAUGE "std:mech.pressure_gauge"
#define STD_MECH_TORQUE "std:mech.torque"
#define STD_MEDIA_AUDIO_REF "std:media.audio_ref"
#define STD_MEDIA_IMAGE_REF "std:media.image_ref"
#define STD_MOTION_ACCELERATION "std:motion.acceleration"
#define STD_MOTION_POSITION "std:motion.position"
#define STD_MOTION_ROTATION "std:motion.rotation"
#define STD_MOTION_VELOCITY "std:motion.velocity"
#define STD_NET_RSSI "std:net.rssi"
#define STD_NET_UPTIME "std:net.uptime"
#define STD_TIME_DURATION "std:time.duration"
#define STD_TIME_TIMESTAMP "std:time.timestamp"

/* Typed refs (default unit + preferred encoding) */
#define STD_ACT_COMMAND_REF "std:act.command#-:enum"
#define STD_ACT_POWER_REF "std:act.power#-:enum"
#define STD_ACT_SETPOINT_REF "std:act.setpoint#-:f32"
#define STD_ELEC_BATTERY_SOC_REF "std:elec.battery_soc#%:f32"
#define STD_ELEC_CURRENT_REF "std:elec.current#A:f32"
#define STD_ELEC_ENERGY_REF "std:elec.energy#Wh:f32"
#define STD_ELEC_FREQUENCY_REF "std:elec.frequency#Hz:f32"
#define STD_ELEC_POWER_REF "std:elec.power#W:f32"
#define STD_ELEC_VOLTAGE_REF "std:elec.voltage#V:f32"
#define STD_ENV_CO2_REF "std:env.co2#ppm:f32"
#define STD_ENV_HUMIDITY_REF "std:env.humidity#%:f32"
#define STD_ENV_ILLUMINANCE_REF "std:env.illuminance#lx:f32"
#define STD_ENV_PM25_REF "std:env.pm25#ug/m3:f32"
#define STD_ENV_PRESSURE_REF "std:env.pressure#hPa:f32"
#define STD_ENV_TEMPERATURE_REF "std:env.temperature#Cel:f32"
#define STD_ENV_VOC_REF "std:env.voc#ppm:f32"
#define STD_GEO_ALTITUDE_REF "std:geo.altitude#m:f32"
#define STD_GEO_GEOPOINT_REF "std:geo.geopoint#-:record"
#define STD_GEO_HEADING_REF "std:geo.heading#deg:f32"
#define STD_HEALTH_BODY_TEMP_REF "std:health.body_temp#Cel:f32"
#define STD_HEALTH_HEART_RATE_REF "std:health.heart_rate#/min:u8"
#define STD_HEALTH_SPO2_REF "std:health.spo2#%:u8"
#define STD_ID_DEVICE_REF "std:id.device#-:utf8"
#define STD_ID_MAC_REF "std:id.mac#-:utf8"
#define STD_ID_SERIAL_REF "std:id.serial#-:utf8"
#define STD_ID_UUID_REF "std:id.uuid#-:utf8"
#define STD_LOGICAL_FLAG_REF "std:logical.flag#-:bool"
#define STD_LOGICAL_LEVEL_REF "std:logical.level#%:u8"
#define STD_LOGICAL_MODE_REF "std:logical.mode#-:enum"
#define STD_MECH_FLOW_REF "std:mech.flow#L/min:f32"
#define STD_MECH_FORCE_REF "std:mech.force#N:f32"
#define STD_MECH_PRESSURE_GAUGE_REF "std:mech.pressure_gauge#Pa:f32"
#define STD_MECH_TORQUE_REF "std:mech.torque#N.m:f32"
#define STD_MEDIA_AUDIO_REF_REF "std:media.audio_ref#-:utf8"
#define STD_MEDIA_IMAGE_REF_REF "std:media.image_ref#-:utf8"
#define STD_MOTION_ACCELERATION_REF "std:motion.acceleration#m/s2:f32"
#define STD_MOTION_POSITION_REF "std:motion.position#m:f32"
#define STD_MOTION_ROTATION_REF "std:motion.rotation#deg:f32"
#define STD_MOTION_VELOCITY_REF "std:motion.velocity#m/s:f32"
#define STD_NET_RSSI_REF "std:net.rssi#dB:i16"
#define STD_NET_UPTIME_REF "std:net.uptime#s:i32"
#define STD_TIME_DURATION_REF "std:time.duration#s:f32"
#define STD_TIME_TIMESTAMP_REF "std:time.timestamp#s:i32"

/* Profile identifiers */
#define STD_PROFILE_ACTUATOR "actuator"
#define STD_PROFILE_GPS "gps"
#define STD_PROFILE_METER "meter"
#define STD_PROFILE_THERMOMETER "thermometer"

typedef struct standart_type_info {
  const char *id;
  const char *kind;
  const char *domain;
  const char *default_unit;
  const char *status;
} standart_type_info_t;

static const standart_type_info_t STANDART_TYPES[] = {
  { "std:act.command", "command", "act", "-", "stable" },
  { "std:act.power", "enum", "act", "-", "stable" },
  { "std:act.setpoint", "quantity", "act", "-", "stable" },
  { "std:elec.battery_soc", "quantity", "elec", "%", "stable" },
  { "std:elec.current", "quantity", "elec", "A", "stable" },
  { "std:elec.energy", "quantity", "elec", "Wh", "stable" },
  { "std:elec.frequency", "quantity", "elec", "Hz", "stable" },
  { "std:elec.power", "quantity", "elec", "W", "stable" },
  { "std:elec.voltage", "quantity", "elec", "V", "stable" },
  { "std:env.co2", "quantity", "env", "ppm", "stable" },
  { "std:env.humidity", "quantity", "env", "%", "stable" },
  { "std:env.illuminance", "quantity", "env", "lx", "stable" },
  { "std:env.pm25", "quantity", "env", "ug/m3", "stable" },
  { "std:env.pressure", "quantity", "env", "hPa", "stable" },
  { "std:env.temperature", "quantity", "env", "Cel", "stable" },
  { "std:env.voc", "quantity", "env", "ppm", "stable" },
  { "std:geo.altitude", "quantity", "geo", "m", "stable" },
  { "std:geo.geopoint", "spatial", "geo", "-", "stable" },
  { "std:geo.heading", "quantity", "geo", "deg", "stable" },
  { "std:health.body_temp", "quantity", "health", "Cel", "stable" },
  { "std:health.heart_rate", "quantity", "health", "/min", "stable" },
  { "std:health.spo2", "quantity", "health", "%", "stable" },
  { "std:id.device", "identity", "id", "-", "stable" },
  { "std:id.mac", "identity", "id", "-", "stable" },
  { "std:id.serial", "identity", "id", "-", "stable" },
  { "std:id.uuid", "identity", "id", "-", "stable" },
  { "std:logical.flag", "logical", "logical", "-", "stable" },
  { "std:logical.level", "quantity", "logical", "%", "stable" },
  { "std:logical.mode", "enum", "logical", "-", "stable" },
  { "std:mech.flow", "quantity", "mech", "L/min", "stable" },
  { "std:mech.force", "quantity", "mech", "N", "stable" },
  { "std:mech.pressure_gauge", "quantity", "mech", "Pa", "stable" },
  { "std:mech.torque", "quantity", "mech", "N.m", "stable" },
  { "std:media.audio_ref", "media", "media", "-", "stable" },
  { "std:media.image_ref", "media", "media", "-", "stable" },
  { "std:motion.acceleration", "quantity", "motion", "m/s2", "stable" },
  { "std:motion.position", "quantity", "motion", "m", "stable" },
  { "std:motion.rotation", "quantity", "motion", "deg", "stable" },
  { "std:motion.velocity", "quantity", "motion", "m/s", "stable" },
  { "std:net.rssi", "quantity", "net", "dB", "stable" },
  { "std:net.uptime", "quantity", "net", "s", "stable" },
  { "std:time.duration", "temporal", "time", "s", "stable" },
  { "std:time.timestamp", "temporal", "time", "s", "stable" },
};

#endif /* STANDART_H */
