#!/usr/bin/env node
/**
 * Generate C header and TypeScript types from STANDART v0.2 registry.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

function readYaml(filePath) {
  return YAML.parse(fs.readFileSync(filePath, "utf8"));
}

function loadTypes() {
  const dir = path.join(root, "registry", "types");
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => readYaml(path.join(dir, f)))
    .sort((a, b) => a.path.localeCompare(b.path));
}

function loadProfiles() {
  const dir = path.join(root, "registry", "profiles");
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => readYaml(path.join(dir, f)))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function pathMacro(p) {
  return (
    "STD_PATH_" +
    p
      .replace(/\./g, "_")
      .toUpperCase()
  );
}

function sidMacro(p) {
  return (
    "STD_SID_" +
    p
      .replace(/\./g, "_")
      .toUpperCase()
  );
}

function generateC(types, profiles, version) {
  const lines = [];
  lines.push("/* Generated by tools/codegen.mjs — do not edit by hand. */");
  lines.push("/* SPDX-License-Identifier: Apache-2.0 */");
  lines.push("#ifndef STANDART_H");
  lines.push("#define STANDART_H");
  lines.push("");
  lines.push(`#define STANDART_REGISTRY_VERSION "${version}"`);
  lines.push(`#define STANDART_TYPE_COUNT ${types.length}`);
  lines.push(`#define STANDART_PROFILE_COUNT ${profiles.length}`);
  lines.push("");
  lines.push("/* Short ids (wire) */");
  for (const t of types) {
    lines.push(`#define ${sidMacro(t.path)} "${t.sid}"`);
  }
  lines.push("");
  lines.push("/* Full hierarchical paths */");
  for (const t of types) {
    lines.push(`#define ${pathMacro(t.path)} "${t.path}"`);
  }
  lines.push("");
  lines.push("/* Profile identifiers */");
  for (const p of profiles) {
    lines.push(`#define STD_PROFILE_${p.id.toUpperCase()} "${p.id}"`);
  }
  lines.push("");
  lines.push("typedef struct standart_type_info {");
  lines.push("  const char *sid;");
  lines.push("  const char *path;");
  lines.push("  const char *kind;");
  lines.push("  const char *unit;");
  lines.push("  const char *fingerprint;");
  lines.push("  const char *status;");
  lines.push("} standart_type_info_t;");
  lines.push("");
  lines.push("static const standart_type_info_t STANDART_TYPES[] = {");
  for (const t of types) {
    lines.push(
      `  { "${t.sid}", "${t.path}", "${t.kind}", "${t.unit}", "${t.fingerprint}", "${t.status}" },`
    );
  }
  lines.push("};");
  lines.push("");
  lines.push("#endif /* STANDART_H */");
  lines.push("");
  return lines.join("\n");
}

function tsKey(p) {
  return p.replace(/\./g, "_").toUpperCase();
}

function generateTs(types, profiles, version, checksum) {
  const sidUnion = types.map((t) => `  | ${JSON.stringify(t.sid)}`).join("\n");
  const pathUnion = types.map((t) => `  | ${JSON.stringify(t.path)}`).join("\n");
  const profileUnion = profiles.map((p) => `  | ${JSON.stringify(p.id)}`).join("\n");

  const typeConsts = types
    .map((t) => `  ${tsKey(t.path)}: ${JSON.stringify(t.sid)} as const,`)
    .join("\n");

  const pathConsts = types
    .map((t) => `  ${tsKey(t.path)}: ${JSON.stringify(t.path)} as const,`)
    .join("\n");

  const cards = types.map((t) => ({
    sid: t.sid,
    path: t.path,
    kind: t.kind,
    unit: t.unit,
    encodings: t.encodings,
    sensitivity: t.sensitivity,
    status: t.status,
    title: t.title,
    fingerprint: t.fingerprint,
    ...(t.aliases ? { aliases: t.aliases } : {}),
    ...(t.range ? { range: t.range } : {}),
    ...(t.enumValues ? { enumValues: t.enumValues } : {}),
    ...(t.description ? { description: t.description } : {}),
  }));

  const profileData = profiles.map((p) => ({
    id: p.id,
    version: p.version,
    title: p.title,
    description: p.description,
    required: p.required,
    optional: p.optional || [],
  }));

  return `/* Generated by tools/codegen.mjs — do not edit by hand. */
/* SPDX-License-Identifier: Apache-2.0 */

export const STANDART_REGISTRY_VERSION = ${JSON.stringify(version)} as const;
export const STANDART_REGISTRY_CHECKSUM = ${JSON.stringify(checksum)} as const;

export type StandartSid =
${sidUnion};

export type StandartPath =
${pathUnion};

export type StandartProfileId =
${profileUnion};

export type StandartKind =
  | "quantity"
  | "enum"
  | "identity"
  | "temporal"
  | "spatial"
  | "logical"
  | "media"
  | "structured"
  | "event"
  | "command";

export type StandartEncoding =
  | "bool"
  | "u8"
  | "i16"
  | "i32"
  | "f32"
  | "f64"
  | "utf8"
  | "bytes"
  | "record"
  | "enum";

export type StandartSensitivity = "public" | "internal" | "personal" | "restricted";
export type StandartStatus = "stable" | "draft" | "deprecated";

export interface LocalizedString {
  ru: string;
  en: string;
}

export interface StandartTypeCard {
  sid: StandartSid;
  path: StandartPath;
  kind: StandartKind;
  unit: string;
  encodings: StandartEncoding[];
  sensitivity: StandartSensitivity;
  status: StandartStatus;
  title: LocalizedString;
  fingerprint: string;
  aliases?: { ru?: string; short?: string; legacy?: string };
  description?: LocalizedString;
  range?: { min: number; max: number; unit?: string };
  enumValues?: string[];
}

export interface StandartProfile {
  id: StandartProfileId;
  version: string;
  title: LocalizedString;
  description?: LocalizedString;
  required: StandartSid[];
  optional: StandartSid[];
}

/** Minimum wire reading: device sends sid + value */
export interface StandartReading {
  sid: StandartSid;
  v: unknown;
  t?: number;
}

/** Short ids for wire / firmware */
export const Sid = {
${typeConsts}
} as const;

/** Full hierarchical paths */
export const Path = {
${pathConsts}
} as const;

export const TYPES: readonly StandartTypeCard[] = ${JSON.stringify(cards, null, 2)} as const;

export const PROFILES: readonly StandartProfile[] = ${JSON.stringify(profileData, null, 2)} as const;

export function getBySid(sid: string): StandartTypeCard | undefined {
  return TYPES.find((t) => t.sid === sid);
}

export function getByPath(path: string): StandartTypeCard | undefined {
  return TYPES.find((t) => t.path === path);
}

export function getProfile(id: StandartProfileId): StandartProfile | undefined {
  return PROFILES.find((p) => p.id === id);
}

export function isSid(value: string): value is StandartSid {
  return TYPES.some((t) => t.sid === value);
}
`;
}

function main() {
  const versionDoc = readYaml(path.join(root, "registry", "version.yaml"));
  const version = versionDoc.version;
  const types = loadTypes();
  const profiles = loadProfiles();

  let checksum = "";
  const manifestPath = path.join(root, "registry", "manifest.json");
  if (fs.existsSync(manifestPath)) {
    checksum = JSON.parse(fs.readFileSync(manifestPath, "utf8")).registry_checksum || "";
  }

  fs.mkdirSync(path.join(root, "sdk", "c"), { recursive: true });
  fs.mkdirSync(path.join(root, "sdk", "ts"), { recursive: true });

  fs.writeFileSync(path.join(root, "sdk", "c", "standart.h"), generateC(types, profiles, version));
  fs.writeFileSync(
    path.join(root, "sdk", "ts", "index.ts"),
    generateTs(types, profiles, version, checksum)
  );
  fs.writeFileSync(
    path.join(root, "sdk", "ts", "package.json"),
    JSON.stringify(
      {
        name: "@standart/types",
        version,
        description: "STANDART generated TypeScript type registry (hybrid path/sid)",
        type: "module",
        main: "index.ts",
        types: "index.ts",
        license: "Apache-2.0",
        files: ["index.ts", "README.md"],
      },
      null,
      2
    ) + "\n"
  );
  fs.writeFileSync(
    path.join(root, "sdk", "ts", "README.md"),
    `# @standart/types

Generated TypeScript bindings for the STANDART hybrid classifier.

\`\`\`ts
import { Sid, Path, getBySid, STANDART_REGISTRY_CHECKSUM } from "./index.ts";

getBySid(Sid.PHYSICAL_ENVIRONMENT_TEMPERATURE);
// wire: { sid: Sid.PHYSICAL_ENVIRONMENT_TEMPERATURE, v: 23.4 }
\`\`\`

Regenerate: \`npm run codegen\` from repo root.
`
  );

  console.log(
    `STANDART codegen OK: ${types.length} types → sdk/c/standart.h, sdk/ts/index.ts`
  );
}

main();
