#!/usr/bin/env node
/**
 * Generate C header and TypeScript types from the STANDART registry.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

function readYaml(filePath) {
  return YAML.parse(fs.readFileSync(filePath, "utf8"));
}

function loadTypes() {
  const dir = path.join(root, "registry", "types");
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => readYaml(path.join(dir, f)))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function loadProfiles() {
  const dir = path.join(root, "registry", "profiles");
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => readYaml(path.join(dir, f)))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function cMacroName(typeId) {
  // std:env.temperature -> STD_ENV_TEMPERATURE
  return typeId
    .replace(/^std:/, "STD_")
    .replace(/\./g, "_")
    .toUpperCase();
}

function generateC(types, profiles, version) {
  const lines = [];
  lines.push("/* Generated by tools/codegen.mjs — do not edit by hand. */");
  lines.push("/* SPDX-License-Identifier: Apache-2.0 */");
  lines.push("#ifndef STANDART_H");
  lines.push("#define STANDART_H");
  lines.push("");
  lines.push(`#define STANDART_REGISTRY_VERSION "${version}"`);
  lines.push(`#define STANDART_TYPE_COUNT ${types.length}`);
  lines.push(`#define STANDART_PROFILE_COUNT ${profiles.length}`);
  lines.push("");
  lines.push("/* Type identifiers */");
  for (const t of types) {
    const mac = cMacroName(t.id);
    lines.push(`#define ${mac} "${t.id}"`);
  }
  lines.push("");
  lines.push("/* Typed refs (default unit + preferred encoding) */");
  for (const t of types) {
    const mac = cMacroName(t.id) + "_REF";
    const enc = t.encodings[0];
    lines.push(`#define ${mac} "${t.id}#${t.defaultUnit}:${enc}"`);
  }
  lines.push("");
  lines.push("/* Profile identifiers */");
  for (const p of profiles) {
    const mac = `STD_PROFILE_${p.id.toUpperCase()}`;
    lines.push(`#define ${mac} "${p.id}"`);
  }
  lines.push("");
  lines.push("typedef struct standart_type_info {");
  lines.push("  const char *id;");
  lines.push("  const char *kind;");
  lines.push("  const char *domain;");
  lines.push("  const char *default_unit;");
  lines.push("  const char *status;");
  lines.push("} standart_type_info_t;");
  lines.push("");
  lines.push("static const standart_type_info_t STANDART_TYPES[] = {");
  for (const t of types) {
    lines.push(
      `  { "${t.id}", "${t.kind}", "${t.domain}", "${t.defaultUnit}", "${t.status}" },`
    );
  }
  lines.push("};");
  lines.push("");
  lines.push("#endif /* STANDART_H */");
  lines.push("");
  return lines.join("\n");
}

function generateTs(types, profiles, version) {
  const typeIds = types.map((t) => JSON.stringify(t.id));
  const profileIds = profiles.map((p) => JSON.stringify(p.id));

  const typeConsts = types
    .map((t) => {
      const key = t.id
        .replace(/^std:/, "")
        .replace(/\./g, "_")
        .toUpperCase();
      return `  ${key}: ${JSON.stringify(t.id)} as const,`;
    })
    .join("\n");

  const cards = types.map((t) => {
    const card = {
      id: t.id,
      kind: t.kind,
      domain: t.domain,
      defaultUnit: t.defaultUnit,
      encodings: t.encodings,
      sensitivity: t.sensitivity,
      status: t.status,
      title: t.title,
    };
    if (t.range) card.range = t.range;
    if (t.enumValues) card.enumValues = t.enumValues;
    if (t.description) card.description = t.description;
    return card;
  });

  const profileData = profiles.map((p) => ({
    id: p.id,
    version: p.version,
    title: p.title,
    description: p.description,
    required: p.required,
    optional: p.optional || [],
  }));

  return `/* Generated by tools/codegen.mjs — do not edit by hand. */
/* SPDX-License-Identifier: Apache-2.0 */

export const STANDART_REGISTRY_VERSION = ${JSON.stringify(version)} as const;

export type StandartTypeId =
${typeIds.map((id) => `  | ${id}`).join("\n")};

export type StandartProfileId =
${profileIds.map((id) => `  | ${id}`).join("\n")};

export type StandartKind =
  | "quantity"
  | "enum"
  | "identity"
  | "temporal"
  | "spatial"
  | "logical"
  | "media"
  | "structured"
  | "event"
  | "command";

export type StandartEncoding =
  | "bool"
  | "u8"
  | "i16"
  | "i32"
  | "f32"
  | "f64"
  | "utf8"
  | "bytes"
  | "record"
  | "enum";

export type StandartSensitivity = "public" | "internal" | "personal" | "restricted";
export type StandartStatus = "stable" | "draft" | "deprecated";

export interface LocalizedString {
  ru: string;
  en: string;
}

export interface StandartTypeCard {
  id: StandartTypeId;
  kind: StandartKind;
  domain: string;
  defaultUnit: string;
  encodings: StandartEncoding[];
  sensitivity: StandartSensitivity;
  status: StandartStatus;
  title: LocalizedString;
  description?: LocalizedString;
  range?: { min: number; max: number; unit: string };
  enumValues?: string[];
}

export interface StandartProfile {
  id: StandartProfileId;
  version: string;
  title: LocalizedString;
  description?: LocalizedString;
  required: StandartTypeId[];
  optional: StandartTypeId[];
}

export interface StandartReading {
  type: StandartTypeId;
  unit: string;
  enc: StandartEncoding;
  v: unknown;
  t?: number;
}

export const TypeId = {
${typeConsts}
} as const;

export const TYPES: readonly StandartTypeCard[] = ${JSON.stringify(cards, null, 2)} as const;

export const PROFILES: readonly StandartProfile[] = ${JSON.stringify(profileData, null, 2)} as const;

export function getType(id: StandartTypeId): StandartTypeCard | undefined {
  return TYPES.find((t) => t.id === id);
}

export function getProfile(id: StandartProfileId): StandartProfile | undefined {
  return PROFILES.find((p) => p.id === id);
}

export function isTypeId(value: string): value is StandartTypeId {
  return TYPES.some((t) => t.id === value);
}
`;
}

function generateTsPackageJson() {
  return `{
  "name": "@standart/types",
  "version": "0.1.0",
  "description": "STANDART generated TypeScript type registry",
  "type": "module",
  "main": "index.ts",
  "types": "index.ts",
  "license": "Apache-2.0",
  "files": ["index.ts", "README.md"]
}
`;
}

function generateTsReadme() {
  return `# @standart/types

Generated TypeScript bindings for the STANDART device type registry.

\`\`\`ts
import { TypeId, getType, STANDART_REGISTRY_VERSION } from "./index.ts";

console.log(STANDART_REGISTRY_VERSION);
console.log(getType(TypeId.ENV_TEMPERATURE));
\`\`\`

Regenerate with \`node tools/codegen.mjs\` from the repository root.
`;
}

function main() {
  const versionDoc = readYaml(path.join(root, "registry", "version.yaml"));
  const version = versionDoc.version;
  const types = loadTypes();
  const profiles = loadProfiles();

  const cPath = path.join(root, "sdk", "c", "standart.h");
  const tsPath = path.join(root, "sdk", "ts", "index.ts");
  const tsPkg = path.join(root, "sdk", "ts", "package.json");
  const tsReadme = path.join(root, "sdk", "ts", "README.md");

  fs.mkdirSync(path.dirname(cPath), { recursive: true });
  fs.mkdirSync(path.dirname(tsPath), { recursive: true });

  fs.writeFileSync(cPath, generateC(types, profiles, version));
  fs.writeFileSync(tsPath, generateTs(types, profiles, version));
  fs.writeFileSync(tsPkg, generateTsPackageJson());
  fs.writeFileSync(tsReadme, generateTsReadme());

  console.log(
    `STANDART codegen OK: ${types.length} types → sdk/c/standart.h, sdk/ts/index.ts`
  );
}

main();
